version: 2
jobs:
  build-jar:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/project

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      # IMPORTANT - circleci needs the AWS credentials setup correctly
      # with a user that can access the s3 bucket used for the maven dependencies

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: ./gradlew build

      - persist_to_workspace:
          root: .
          paths:
            - gradle.properties
            - build/libs
            - Dockerfile
            - k8

  build-docker:
    docker:
      - image: quay.io/thoughtworks_aelab/di-circleci-platform-agent:3.8.23
        auth:
          username: $DOCKER_USER
          password: $QUAY_TOKEN
    working_directory: ~/project

    steps:
      - attach_workspace:
          at: ~/project
      - run: echo 'export DOCKER_TAG="`grep 'version' gradle.properties|cut -d'=' -f2`-$CIRCLE_BUILD_NUM"' >> $BASH_ENV

      - run: docker build --build-arg JAR_FILE=build/libs/customerservice-lastest.jar -t quay.io/thoughtworks_aelab/customerservice:$DOCKER_TAG .

workflows:
  version: 2

  btd:
    jobs:
      - build-jar
      - build-docker:
          requires:
            - build-jar