# label of status: released' indicates the version that's considered released in
# that namespace
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}-v{{LATEST_VERSION}}
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{SERVICE_NAME}}
        version: {{LATEST_VERSION}}
        status: pending
    spec:
      imagePullSecrets:
      - name: thoughtworks-aelab-di-circleci-quayio-deploy-user-pull-secret
      containers:
      - name: service
        image: quay.io/thoughtworks_aelab/{{SERVICE_NAME}}:{{DOCKER_TAG}}
        imagePullPolicy: Always
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_ID
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
          - name: service
            containerPort: 8082
          - name: readiness
            containerPort: 8083
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
